import { PlaygroundRoute } from '@app/enums';

/** Kikita UI primitives grouped for the playground navigation. */
export const COMPONENT_GROUPS = [
  {
    id: 'actions',
    label: 'playground.groups.actions',
    components: [
      { id: PlaygroundRoute.Button, label: 'playground.components.button' },
      { id: PlaygroundRoute.IconButton, label: 'playground.components.iconButton' },
      { id: PlaygroundRoute.Link, label: 'playground.components.link' },
      { id: PlaygroundRoute.Menu, label: 'playground.components.menu' },
      { id: PlaygroundRoute.CommandPalette, label: 'playground.components.commandPalette' },
      { id: PlaygroundRoute.Pagination, label: 'playground.components.pagination' },
    ],
  },
  {
    id: 'forms',
    label: 'playground.groups.forms',
    components: [
      { id: PlaygroundRoute.Calendar, label: 'playground.components.calendar' },
      { id: PlaygroundRoute.CalendarRange, label: 'playground.components.calendarRange' },
      { id: PlaygroundRoute.Checkbox, label: 'playground.components.checkbox' },
      { id: PlaygroundRoute.ColorInput, label: 'playground.components.colorInput' },
      { id: PlaygroundRoute.Combobox, label: 'playground.components.combobox' },
      { id: PlaygroundRoute.DatePicker, label: 'playground.components.datePicker' },
      { id: PlaygroundRoute.Field, label: 'playground.components.field' },
      { id: PlaygroundRoute.FileUpload, label: 'playground.components.fileUpload' },
      { id: PlaygroundRoute.Group, label: 'playground.components.group' },
      { id: PlaygroundRoute.Input, label: 'playground.components.input' },
      { id: PlaygroundRoute.NumberInput, label: 'playground.components.numberInput' },
      { id: PlaygroundRoute.OtpInput, label: 'playground.components.otpInput' },
      { id: PlaygroundRoute.Radio, label: 'playground.components.radio' },
      { id: PlaygroundRoute.Segmented, label: 'playground.components.segmented' },
      { id: PlaygroundRoute.Select, label: 'playground.components.select' },
      { id: PlaygroundRoute.Slider, label: 'playground.components.slider' },
      { id: PlaygroundRoute.Switch, label: 'playground.components.switch' },
      { id: PlaygroundRoute.Textarea, label: 'playground.components.textarea' },
      { id: PlaygroundRoute.TimePicker, label: 'playground.components.timePicker' },
    ],
  },
  {
    id: 'surfaces',
    label: 'playground.groups.surfaces',
    components: [
      { id: PlaygroundRoute.Accordion, label: 'playground.components.accordion' },
      { id: PlaygroundRoute.Breadcrumbs, label: 'playground.components.breadcrumbs' },
      { id: PlaygroundRoute.Card, label: 'playground.components.card' },
      { id: PlaygroundRoute.Carousel, label: 'playground.components.carousel' },
      { id: PlaygroundRoute.Dialog, label: 'playground.components.dialog' },
      { id: PlaygroundRoute.Drawer, label: 'playground.components.drawer' },
      { id: PlaygroundRoute.Dropdown, label: 'playground.components.dropdown' },
      { id: PlaygroundRoute.MediaViewer, label: 'playground.components.mediaViewer' },
      { id: PlaygroundRoute.Popover, label: 'playground.components.popover' },
      { id: PlaygroundRoute.Separator, label: 'playground.components.separator' },
      { id: PlaygroundRoute.Splitter, label: 'playground.components.splitter' },
      { id: PlaygroundRoute.Stepper, label: 'playground.components.stepper' },
      { id: PlaygroundRoute.Tabs, label: 'playground.components.tabs' },
    ],
  },
  {
    id: 'feedback',
    label: 'playground.groups.feedback',
    components: [
      { id: PlaygroundRoute.Alert, label: 'playground.components.alert' },
      { id: PlaygroundRoute.Badge, label: 'playground.components.badge' },
      { id: PlaygroundRoute.EmptyState, label: 'playground.components.emptyState' },
      { id: PlaygroundRoute.Loader, label: 'playground.components.loader' },
      { id: PlaygroundRoute.Progress, label: 'playground.components.progress' },
      { id: PlaygroundRoute.Skeleton, label: 'playground.components.skeleton' },
      { id: PlaygroundRoute.Toast, label: 'playground.components.toast' },
      { id: PlaygroundRoute.Tooltip, label: 'playground.components.tooltip' },
    ],
  },
  {
    id: 'data-identity',
    label: 'playground.groups.dataIdentity',
    components: [
      { id: PlaygroundRoute.Avatar, label: 'playground.components.avatar' },
      { id: PlaygroundRoute.Chart, label: 'playground.components.chart' },
      { id: PlaygroundRoute.Chip, label: 'playground.components.chip' },
      { id: PlaygroundRoute.Icon, label: 'playground.components.icon' },
      { id: PlaygroundRoute.Scrollbar, label: 'playground.components.scrollbar' },
      { id: PlaygroundRoute.Table, label: 'playground.components.table' },
      { id: PlaygroundRoute.Tree, label: 'playground.components.tree' },
      { id: PlaygroundRoute.Typography, label: 'playground.components.typography' },
    ],
  },
] as const;
