/** Kikita UI primitives grouped for the playground navigation. */
export const COMPONENT_GROUPS = [
  {
    id: 'actions',
    label: 'playground.groups.actions',
    components: [
      { id: 'button', label: 'playground.components.button' },
      { id: 'icon-button', label: 'playground.components.iconButton' },
      { id: 'menu', label: 'playground.components.menu' },
      { id: 'command-palette', label: 'playground.components.commandPalette' },
    ],
  },
  {
    id: 'forms',
    label: 'playground.groups.forms',
    components: [
      { id: 'calendar', label: 'playground.components.calendar' },
      { id: 'checkbox', label: 'playground.components.checkbox' },
      { id: 'color-input', label: 'playground.components.colorInput' },
      { id: 'combobox', label: 'playground.components.combobox' },
      { id: 'date-picker', label: 'playground.components.datePicker' },
      { id: 'field', label: 'playground.components.field' },
      { id: 'file-upload', label: 'playground.components.fileUpload' },
      { id: 'group', label: 'playground.components.group' },
      { id: 'input', label: 'playground.components.input' },
      { id: 'number-input', label: 'playground.components.numberInput' },
      { id: 'radio', label: 'playground.components.radio' },
      { id: 'segmented', label: 'playground.components.segmented' },
      { id: 'select', label: 'playground.components.select' },
      { id: 'slider', label: 'playground.components.slider' },
      { id: 'switch', label: 'playground.components.switch' },
      { id: 'textarea', label: 'playground.components.textarea' },
    ],
  },
  {
    id: 'surfaces',
    label: 'playground.groups.surfaces',
    components: [
      { id: 'accordion', label: 'playground.components.accordion' },
      { id: 'breadcrumbs', label: 'playground.components.breadcrumbs' },
      { id: 'card', label: 'playground.components.card' },
      { id: 'dialog', label: 'playground.components.dialog' },
      { id: 'drawer', label: 'playground.components.drawer' },
      { id: 'dropdown', label: 'playground.components.dropdown' },
      { id: 'popover', label: 'playground.components.popover' },
      { id: 'separator', label: 'playground.components.separator' },
      { id: 'stepper', label: 'playground.components.stepper' },
      { id: 'tabs', label: 'playground.components.tabs' },
    ],
  },
  {
    id: 'feedback',
    label: 'playground.groups.feedback',
    components: [
      { id: 'badge', label: 'playground.components.badge' },
      { id: 'empty-state', label: 'playground.components.emptyState' },
      { id: 'loader', label: 'playground.components.loader' },
      { id: 'progress', label: 'playground.components.progress' },
      { id: 'skeleton', label: 'playground.components.skeleton' },
      { id: 'toast', label: 'playground.components.toast' },
      { id: 'tooltip', label: 'playground.components.tooltip' },
    ],
  },
  {
    id: 'data-identity',
    label: 'playground.groups.dataIdentity',
    components: [
      { id: 'avatar', label: 'playground.components.avatar' },
      { id: 'chip', label: 'playground.components.chip' },
      { id: 'icon', label: 'playground.components.icon' },
      { id: 'scrollbar', label: 'playground.components.scrollbar' },
      { id: 'table', label: 'playground.components.table' },
      { id: 'tree', label: 'playground.components.tree' },
    ],
  },
] as const;
