import { DEFAULT_KUI_THEME } from './default-kui-theme.const';
import { KuiOklchColor } from './kui-theme-color.interface';
import { KuiThemeMode } from './kui-theme-mode.type';
import { KuiThemeOptions } from './kui-theme-options.interface';
import {
  KuiColorScaleName,
  KuiCssVariableMap,
  KuiGeneratedTheme,
  KuiPaletteMap,
} from './kui-theme-tokens.interface';

const LIGHTNESS_STOPS = [
  0.97,
  0.93,
  0.87,
  0.78,
  0.67,
  null,
  0.42,
  0.32,
  0.23,
  0.16,
  0.12,
  0.08,
] as const;
const CHROMA_SCALE = [0.08, 0.15, 0.35, 0.6, 0.85, 1, 0.9, 0.75, 0.55, 0.35, 0.22, 0.12] as const;
const SCALE_NAMES: readonly KuiColorScaleName[] = [
  'primary',
  'neutral',
  'success',
  'warning',
  'danger',
  'info',
];
const FALLBACK_INFO_SEED = 'oklch(0.58 0.16 215)';

/** Creates a generated Kikita UI theme from seed tokens. */
export function createKuiTheme(options: KuiThemeOptions = DEFAULT_KUI_THEME): KuiGeneratedTheme {
  const colorSeeds = options.seeds.color;
  const parsedSeeds: Record<KuiColorScaleName, KuiOklchColor> = {
    primary: parseKuiColor(colorSeeds.primary),
    neutral: parseKuiColor(colorSeeds.neutral),
    success: parseKuiColor(colorSeeds.success),
    warning: parseKuiColor(colorSeeds.warning),
    danger: parseKuiColor(colorSeeds.danger),
    info: parseKuiColor(colorSeeds.info ?? FALLBACK_INFO_SEED),
  };

  const palettes = Object.fromEntries(
    SCALE_NAMES.map((scaleName) => [scaleName, createPalette(parsedSeeds[scaleName])]),
  ) as KuiPaletteMap;

  return {
    seeds: createSeedVariables(parsedSeeds),
    palettes,
    paletteVariables: createPaletteVariables(palettes),
    light: createLightSemanticVariables(parsedSeeds),
    dark: createDarkSemanticVariables(parsedSeeds),
    component: createComponentVariables(options),
  };
}

/** Converts a generated theme into a flat CSS variable map for the requested mode. */
export function createKuiThemeVariableMap(
  theme: KuiGeneratedTheme,
  mode: KuiThemeMode = 'light',
): KuiCssVariableMap {
  return {
    ...theme.seeds,
    ...theme.paletteVariables,
    ...(mode === 'light' ? theme.light : theme.dark),
    ...theme.component,
  };
}

/** Serializes CSS variables for a selector. */
export function createKuiThemeCssText(
  theme: KuiGeneratedTheme,
  selector: string,
  mode: KuiThemeMode = 'light',
): string {
  const variables = createKuiThemeVariableMap(theme, mode);
  const declarations = Object.entries(variables)
    .map(([name, value]) => `  ${name}: ${value};`)
    .join('\n');

  return `${selector} {\n${declarations}\n}`;
}

/** Serializes both default light and attribute-driven dark theme CSS. */
export function createKuiThemeStyleSheet(theme: KuiGeneratedTheme): string {
  return [
    createKuiThemeCssText(theme, ':root, [data-kui-theme="light"]', 'light'),
    createKuiThemeCssText(theme, '[data-kui-theme="dark"]', 'dark'),
  ].join('\n\n');
}

function createPalette(seed: KuiOklchColor): readonly string[] {
  return LIGHTNESS_STOPS.map((lightness, index) =>
    formatOklch({
      lightness: lightness ?? seed.lightness,
      chroma: seed.chroma * CHROMA_SCALE[index],
      hue: seed.hue,
    }),
  );
}

function createSeedVariables(seeds: Record<KuiColorScaleName, KuiOklchColor>): KuiCssVariableMap {
  return Object.fromEntries(
    SCALE_NAMES.map((scaleName) => [`--kui-seed-${scaleName}`, formatOklch(seeds[scaleName])]),
  );
}

function createPaletteVariables(palettes: KuiPaletteMap): KuiCssVariableMap {
  return Object.fromEntries(
    SCALE_NAMES.flatMap((scaleName) =>
      palettes[scaleName].map((value, index) => [`--kui-${scaleName}-${index + 1}`, value]),
    ),
  );
}

function createLightSemanticVariables(
  seeds: Record<KuiColorScaleName, KuiOklchColor>,
): KuiCssVariableMap {
  return {
    '--kui-color-bg': 'oklch(0.97 0.01 80)',
    '--kui-color-surface': 'oklch(1 0 0)',
    '--kui-color-surface-elevated': 'oklch(0.99 0.005 80)',
    '--kui-color-surface-sunken': 'oklch(0.95 0.01 80)',
    '--kui-color-border-subtle': 'oklch(0.92 0.008 80)',
    '--kui-color-border': 'oklch(0.88 0.01 80)',
    '--kui-color-border-strong': 'oklch(0.75 0.015 80)',
    '--kui-color-text': 'oklch(0.18 0.01 80)',
    '--kui-color-text-secondary': 'oklch(0.46 0.01 80)',
    '--kui-color-text-disabled': 'oklch(0.70 0.01 80)',
    '--kui-color-primary-fill': 'var(--kui-primary-6)',
    '--kui-color-primary-fill-hover': 'var(--kui-primary-7)',
    '--kui-color-primary-fill-active': 'var(--kui-primary-8)',
    '--kui-color-primary-soft-bg': 'var(--kui-primary-1)',
    '--kui-color-primary-soft-bg-hover': 'var(--kui-primary-2)',
    '--kui-color-primary-soft-bg-active': 'var(--kui-primary-3)',
    '--kui-color-primary-soft-text': 'var(--kui-primary-7)',
    '--kui-color-primary-focus-ring': formatOklch({ ...seeds.primary, alpha: 0.4 }),
    '--kui-color-success-fill': 'var(--kui-success-6)',
    '--kui-color-success-soft-bg': 'var(--kui-success-1)',
    '--kui-color-success-soft-text': 'var(--kui-success-7)',
    '--kui-color-success-soft-border': 'var(--kui-success-4)',
    '--kui-color-warning-fill': 'var(--kui-warning-6)',
    '--kui-color-warning-soft-bg': 'var(--kui-warning-1)',
    '--kui-color-warning-soft-text': 'var(--kui-warning-7)',
    '--kui-color-warning-soft-border': 'var(--kui-warning-4)',
    '--kui-color-danger-fill': 'var(--kui-danger-6)',
    '--kui-color-danger-fill-hover': 'var(--kui-danger-7)',
    '--kui-color-danger-fill-active': 'var(--kui-danger-8)',
    '--kui-color-danger-soft-bg': 'var(--kui-danger-1)',
    '--kui-color-danger-soft-text': 'var(--kui-danger-7)',
    '--kui-color-danger-soft-border': 'var(--kui-danger-4)',
    '--kui-color-info-fill': 'var(--kui-info-6)',
    '--kui-color-info-soft-bg': 'var(--kui-info-1)',
    '--kui-color-info-soft-text': 'var(--kui-info-7)',
    '--kui-color-info-soft-border': 'var(--kui-info-4)',
    '--kui-color-skeleton-bg': 'oklch(0.90 0.01 80)',
    '--kui-color-skeleton-highlight': 'oklch(0.955 0.005 80)',
    '--kui-avatar-p1-bg': 'oklch(0.87 0.08 285)',
    '--kui-avatar-p1-fg': 'oklch(0.25 0.14 285)',
    '--kui-avatar-p2-bg': 'oklch(0.87 0.07 15)',
    '--kui-avatar-p2-fg': 'oklch(0.25 0.12 15)',
    '--kui-avatar-p3-bg': 'oklch(0.87 0.09 55)',
    '--kui-avatar-p3-fg': 'oklch(0.28 0.09 55)',
    '--kui-avatar-p4-bg': 'oklch(0.87 0.08 145)',
    '--kui-avatar-p4-fg': 'oklch(0.25 0.09 145)',
    '--kui-avatar-p5-bg': 'oklch(0.87 0.07 185)',
    '--kui-avatar-p5-fg': 'oklch(0.25 0.09 185)',
    '--kui-avatar-p6-bg': 'oklch(0.87 0.07 220)',
    '--kui-avatar-p6-fg': 'oklch(0.25 0.11 220)',
    '--kui-avatar-p7-bg': 'oklch(0.87 0.08 260)',
    '--kui-avatar-p7-fg': 'oklch(0.25 0.13 260)',
  };
}

function createDarkSemanticVariables(
  seeds: Record<KuiColorScaleName, KuiOklchColor>,
): KuiCssVariableMap {
  return {
    '--kui-color-bg': 'oklch(0.10 0.01 80)',
    '--kui-color-surface': 'oklch(0.14 0.01 80)',
    '--kui-color-surface-elevated': 'oklch(0.18 0.01 80)',
    '--kui-color-surface-sunken': 'oklch(0.08 0.01 80)',
    '--kui-color-border-subtle': 'oklch(0.18 0.01 80)',
    '--kui-color-border': 'oklch(0.22 0.01 80)',
    '--kui-color-border-strong': 'oklch(0.32 0.01 80)',
    '--kui-color-text': 'oklch(0.93 0.01 80)',
    '--kui-color-text-secondary': 'oklch(0.60 0.01 80)',
    '--kui-color-text-disabled': 'oklch(0.35 0.01 80)',
    '--kui-color-primary-fill': 'var(--kui-primary-5)',
    '--kui-color-primary-fill-hover': 'var(--kui-primary-4)',
    '--kui-color-primary-fill-active': 'var(--kui-primary-6)',
    '--kui-color-primary-soft-bg': 'var(--kui-primary-11)',
    '--kui-color-primary-soft-bg-hover': 'var(--kui-primary-10)',
    '--kui-color-primary-soft-bg-active': 'var(--kui-primary-9)',
    '--kui-color-primary-soft-text': 'var(--kui-primary-4)',
    '--kui-color-primary-focus-ring': formatOklch({
      ...seeds.primary,
      lightness: 0.65,
      chroma: seeds.primary.chroma * 0.88,
      alpha: 0.5,
    }),
    '--kui-color-success-fill': 'var(--kui-success-5)',
    '--kui-color-success-soft-bg': 'var(--kui-success-11)',
    '--kui-color-success-soft-text': 'var(--kui-success-4)',
    '--kui-color-success-soft-border': 'var(--kui-success-8)',
    '--kui-color-warning-fill': 'var(--kui-warning-5)',
    '--kui-color-warning-soft-bg': 'var(--kui-warning-11)',
    '--kui-color-warning-soft-text': 'var(--kui-warning-4)',
    '--kui-color-warning-soft-border': 'var(--kui-warning-8)',
    '--kui-color-danger-fill': 'var(--kui-danger-5)',
    '--kui-color-danger-fill-hover': 'var(--kui-danger-4)',
    '--kui-color-danger-fill-active': 'var(--kui-danger-6)',
    '--kui-color-danger-soft-bg': 'var(--kui-danger-11)',
    '--kui-color-danger-soft-text': 'var(--kui-danger-4)',
    '--kui-color-danger-soft-border': 'var(--kui-danger-8)',
    '--kui-color-info-fill': 'var(--kui-info-5)',
    '--kui-color-info-soft-bg': 'var(--kui-info-11)',
    '--kui-color-info-soft-text': 'var(--kui-info-4)',
    '--kui-color-info-soft-border': 'var(--kui-info-8)',
    '--kui-color-skeleton-bg': 'oklch(0.20 0.01 80)',
    '--kui-color-skeleton-highlight': 'oklch(0.27 0.012 80)',
    '--kui-avatar-p1-bg': 'oklch(0.28 0.16 285)',
    '--kui-avatar-p1-fg': 'oklch(0.87 0.08 285)',
    '--kui-avatar-p2-bg': 'oklch(0.28 0.14 15)',
    '--kui-avatar-p2-fg': 'oklch(0.87 0.07 15)',
    '--kui-avatar-p3-bg': 'oklch(0.30 0.10 55)',
    '--kui-avatar-p3-fg': 'oklch(0.87 0.09 55)',
    '--kui-avatar-p4-bg': 'oklch(0.28 0.10 145)',
    '--kui-avatar-p4-fg': 'oklch(0.87 0.08 145)',
    '--kui-avatar-p5-bg': 'oklch(0.28 0.10 185)',
    '--kui-avatar-p5-fg': 'oklch(0.87 0.07 185)',
    '--kui-avatar-p6-bg': 'oklch(0.28 0.12 220)',
    '--kui-avatar-p6-fg': 'oklch(0.87 0.07 220)',
    '--kui-avatar-p7-bg': 'oklch(0.28 0.14 260)',
    '--kui-avatar-p7-fg': 'oklch(0.87 0.08 260)',
  };
}

function createComponentVariables(options: KuiThemeOptions): KuiCssVariableMap {
  const radius = `${options.seeds.radius}px`;
  const density = options.seeds.density;

  return {
    '--kui-font-sans':
      'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    '--kui-font-mono': 'ui-monospace, "SFMono-Regular", Consolas, "Liberation Mono", monospace',
    '--kui-radius-none': '0',
    '--kui-radius-xs': `${Math.max(2, options.seeds.radius - 4)}px`,
    '--kui-radius-sm': `${Math.max(4, options.seeds.radius - 2)}px`,
    '--kui-radius-md': radius,
    '--kui-radius-lg': `${options.seeds.radius + 2}px`,
    '--kui-radius-xl': `${options.seeds.radius + 6}px`,
    '--kui-radius-full': '9999px',
    '--kui-space-1': '4px',
    '--kui-space-2': '8px',
    '--kui-space-3': '12px',
    '--kui-space-4': '16px',
    '--kui-space-5': '20px',
    '--kui-space-6': '24px',
    '--kui-space-8': '32px',
    '--kui-space-12': '48px',
    '--kui-space-16': '64px',
    '--kui-text-2xs-size': '9px',
    '--kui-text-xs-size': '11px',
    '--kui-text-sm-size': '13px',
    '--kui-text-base-size': '14px',
    '--kui-text-md-size': '15px',
    '--kui-text-lg-size': '18px',
    '--kui-text-xl-size': '22px',
    '--kui-text-2xl-size': '28px',
    '--kui-text-3xl-size': '36px',
    '--kui-control-height-xs': '28px',
    '--kui-control-height-sm': '32px',
    '--kui-control-height-md': '40px',
    '--kui-control-height-lg': '44px',
    '--kui-btn-height-compact': '24px',
    '--kui-btn-height-regular': '32px',
    '--kui-btn-height-comfortable': '40px',
    '--kui-btn-px-compact': '8px',
    '--kui-btn-px-regular': '12px',
    '--kui-btn-px-comfortable': '16px',
    '--kui-btn-height': `var(--kui-btn-height-${density})`,
    '--kui-btn-px': `var(--kui-btn-px-${density})`,
    '--kui-btn-padding-inline': 'var(--kui-btn-px)',
    '--kui-btn-radius': 'var(--kui-radius-md)',
    '--kui-btn-gap': '6px',
    '--kui-btn-font-size': 'var(--kui-text-sm-size)',
    '--kui-btn-font-weight': '500',
    '--kui-btn-solid-bg': 'var(--kui-color-primary-fill)',
    '--kui-btn-solid-bg-hov': 'var(--kui-color-primary-fill-hover)',
    '--kui-btn-solid-bg-act': 'var(--kui-color-primary-fill-active)',
    '--kui-btn-solid-fg': 'oklch(1 0 0)',
    '--kui-btn-soft-bg': 'var(--kui-color-primary-soft-bg)',
    '--kui-btn-soft-bg-hov': 'var(--kui-color-primary-soft-bg-hover)',
    '--kui-btn-soft-bg-act': 'var(--kui-color-primary-soft-bg-active)',
    '--kui-btn-soft-fg': 'var(--kui-color-primary-soft-text)',
    '--kui-btn-outline-border': 'var(--kui-color-primary-fill)',
    '--kui-btn-outline-fg': 'var(--kui-color-primary-fill)',
    '--kui-btn-outline-bg-hov': 'var(--kui-color-surface-elevated)',
    '--kui-btn-outline-bg-act': 'var(--kui-color-surface-sunken)',
    '--kui-btn-ghost-fg': 'var(--kui-color-text-secondary)',
    '--kui-btn-ghost-bg-hov': 'var(--kui-color-surface-sunken)',
    '--kui-btn-ghost-bg-act': 'var(--kui-color-surface-elevated)',
    '--kui-btn-danger-bg': 'var(--kui-color-danger-fill)',
    '--kui-btn-danger-bg-hov': 'var(--kui-color-danger-fill-hover)',
    '--kui-btn-danger-bg-act': 'var(--kui-color-danger-fill-active)',
    '--kui-btn-danger-fg': 'oklch(1 0 0)',
    '--kui-btn-bg': 'var(--kui-btn-solid-bg)',
    '--kui-btn-bg-hover': 'var(--kui-btn-solid-bg-hov)',
    '--kui-btn-bg-active': 'var(--kui-btn-solid-bg-act)',
    '--kui-btn-color': 'var(--kui-btn-solid-fg)',
    '--kui-btn-secondary-bg': 'var(--kui-btn-soft-bg)',
    '--kui-btn-secondary-bg-hover': 'var(--kui-btn-soft-bg-hov)',
    '--kui-btn-secondary-color': 'var(--kui-btn-soft-fg)',
    '--kui-btn-outline-bg-hover': 'var(--kui-btn-outline-bg-hov)',
    '--kui-btn-ghost-bg-hover': 'var(--kui-btn-ghost-bg-hov)',
    '--kui-btn-focus-ring-w': '3px',
    '--kui-btn-focus-ring-off': '2px',
    '--kui-btn-focus-ring-color': 'var(--kui-color-primary-focus-ring)',
    '--kui-btn-focus-ring-width': 'var(--kui-btn-focus-ring-w)',
    '--kui-btn-focus-ring-offset': 'var(--kui-btn-focus-ring-off)',
    '--kui-btn-focus-ring': '0 0 0 3px var(--kui-color-primary-focus-ring)',
    '--kui-btn-disabled-opacity': '0.5',
    '--kui-duration-fast': '100ms',
    '--kui-duration-base': '160ms',
    '--kui-ease': 'cubic-bezier(0.16, 1, 0.3, 1)',
    '--kui-group-gap': 'var(--kui-space-2)',
    '--kui-group-collapsed-gap': '-1px',
    '--kui-field-gap': 'var(--kui-space-1)',
    '--kui-field-label-size': 'var(--kui-text-sm-size)',
    '--kui-field-label-weight': '600',
    '--kui-field-label-color': 'var(--kui-color-text)',
    '--kui-field-hint-size': 'var(--kui-text-xs-size)',
    '--kui-field-hint-color': 'var(--kui-color-text-secondary)',
    '--kui-field-error-color': 'var(--kui-color-danger-fill)',
    '--kui-field-required-color': 'var(--kui-color-danger-fill)',
    '--kui-field-affix-gap': 'var(--kui-space-2)',
    '--kui-field-affix-text': 'var(--kui-color-text)',
    '--kui-field-affix-text-muted': 'var(--kui-color-text-secondary)',
    '--kui-field-affix-icon-size': '16px',
    '--kui-field-affix-max-inline-size': '40%',
    '--kui-field-message-gap': 'var(--kui-space-1)',
    '--kui-field-message-icon-size': '12px',
    '--kui-field-message-icon-offset': '1px',
    '--kui-field-spinner-size': '14px',
    '--kui-field-spinner-border-width': '2px',
    '--kui-field-spinner-border': 'var(--kui-color-border)',
    '--kui-field-spinner-border-active': 'var(--kui-color-primary-fill)',
    '--kui-field-spinner-duration': '800ms',
    '--kui-field-spinner-duration-reduced': '2000ms',
    '--kui-input-height': 'var(--kui-btn-height)',
    '--kui-input-px': 'var(--kui-btn-px)',
    '--kui-input-padding-inline': 'var(--kui-input-px)',
    '--kui-input-radius': 'var(--kui-radius-md)',
    '--kui-input-bg': 'var(--kui-color-surface)',
    '--kui-input-bg-disabled': 'var(--kui-color-surface-sunken)',
    '--kui-input-text': 'var(--kui-color-text)',
    '--kui-input-color': 'var(--kui-color-text)',
    '--kui-input-border': 'var(--kui-color-border)',
    '--kui-input-border-hover': 'var(--kui-color-border-strong)',
    '--kui-input-border-focus': 'var(--kui-color-primary-fill)',
    '--kui-input-border-error': 'var(--kui-color-danger-fill)',
    '--kui-input-border-invalid': 'var(--kui-color-danger-fill)',
    '--kui-input-border-width': '1px',
    '--kui-input-border-width-focus': '1px',
    '--kui-input-placeholder': 'var(--kui-color-text-disabled)',
    '--kui-input-placeholder-color': 'var(--kui-input-placeholder)',
    '--kui-input-focus-ring': '0 0 0 3px var(--kui-color-primary-focus-ring)',
    '--kui-checkbox-size': '18px',
    '--kui-checkbox-radius': 'var(--kui-radius-sm)',
    '--kui-checkbox-bg': 'var(--kui-color-surface)',
    '--kui-checkbox-border': 'var(--kui-color-border)',
    '--kui-checkbox-border-hover': 'var(--kui-color-border-strong)',
    '--kui-checkbox-border-error': 'var(--kui-color-danger-fill)',
    '--kui-checkbox-checked-bg': 'var(--kui-color-primary-fill)',
    '--kui-checkbox-checked-border': 'var(--kui-color-primary-fill)',
    '--kui-checkbox-mark': 'oklch(1 0 0)',
    '--kui-checkbox-border-width': '1px',
    '--kui-checkbox-focus-ring-w': '3px',
    '--kui-checkbox-focus-ring-off': '2px',
    '--kui-checkbox-focus-ring-color': 'var(--kui-color-primary-focus-ring)',
    '--kui-radio-size': '18px',
    '--kui-radio-bg': 'var(--kui-color-surface)',
    '--kui-radio-border': 'var(--kui-color-border)',
    '--kui-radio-border-hover': 'var(--kui-color-border-strong)',
    '--kui-radio-border-error': 'var(--kui-color-danger-fill)',
    '--kui-radio-checked-bg': 'var(--kui-color-primary-fill)',
    '--kui-radio-checked-border': 'var(--kui-color-primary-fill)',
    '--kui-radio-dot': 'oklch(1 0 0)',
    '--kui-radio-border-width': '1px',
    '--kui-radio-focus-ring-w': '3px',
    '--kui-radio-focus-ring-off': '2px',
    '--kui-radio-focus-ring-color': 'var(--kui-color-primary-focus-ring)',
    '--kui-switch-width': '38px',
    '--kui-switch-height': '22px',
    '--kui-switch-thumb-size': '16px',
    '--kui-switch-thumb-offset': '2px',
    '--kui-switch-thumb-translate': '16px',
    '--kui-switch-radius': '999px',
    '--kui-switch-bg': 'var(--kui-color-surface-sunken)',
    '--kui-switch-border': 'var(--kui-color-border)',
    '--kui-switch-border-hover': 'var(--kui-color-border-strong)',
    '--kui-switch-border-error': 'var(--kui-color-danger-fill)',
    '--kui-switch-checked-bg': 'var(--kui-color-primary-fill)',
    '--kui-switch-checked-border': 'var(--kui-color-primary-fill)',
    '--kui-switch-thumb-bg': 'var(--kui-color-text-secondary)',
    '--kui-switch-checked-thumb-bg': 'oklch(1 0 0)',
    '--kui-switch-border-width': '1px',
    '--kui-switch-focus-ring-w': '3px',
    '--kui-switch-focus-ring-off': '2px',
    '--kui-switch-focus-ring-color': 'var(--kui-color-primary-focus-ring)',
    '--kui-switch-thumb-shadow': '0 1px 2px oklch(0 0 0 / 0.22)',
    '--kui-badge-height': '22px',
    '--kui-badge-px': 'var(--kui-space-2)',
    '--kui-badge-gap': 'var(--kui-space-1)',
    '--kui-badge-radius': 'var(--kui-radius-full)',
    '--kui-badge-font-size': 'var(--kui-text-xs-size)',
    '--kui-badge-font-weight': '600',
    '--kui-badge-neutral-bg': 'var(--kui-color-surface-elevated)',
    '--kui-badge-neutral-fg': 'var(--kui-color-text-secondary)',
    '--kui-badge-neutral-border': 'var(--kui-color-border)',
    '--kui-badge-primary-bg': 'var(--kui-color-primary-soft-bg)',
    '--kui-badge-primary-fg': 'var(--kui-color-primary-soft-text)',
    '--kui-badge-primary-border': 'var(--kui-color-primary-fill)',
    '--kui-badge-success-bg': 'var(--kui-color-success-soft-bg)',
    '--kui-badge-success-fg': 'var(--kui-color-success-soft-text)',
    '--kui-badge-success-border': 'var(--kui-color-success-soft-border)',
    '--kui-badge-warning-bg': 'var(--kui-color-warning-soft-bg)',
    '--kui-badge-warning-fg': 'var(--kui-color-warning-soft-text)',
    '--kui-badge-warning-border': 'var(--kui-color-warning-soft-border)',
    '--kui-badge-danger-bg': 'var(--kui-color-danger-soft-bg)',
    '--kui-badge-danger-fg': 'var(--kui-color-danger-soft-text)',
    '--kui-badge-danger-border': 'var(--kui-color-danger-soft-border)',
    '--kui-badge-info-bg': 'var(--kui-color-info-soft-bg)',
    '--kui-badge-info-fg': 'var(--kui-color-info-soft-text)',
    '--kui-badge-info-border': 'var(--kui-color-info-soft-border)',
    '--kui-loader-size': '20px',
    '--kui-loader-track': 'var(--kui-color-surface-sunken)',
    '--kui-loader-fill': 'var(--kui-color-primary-fill)',
    '--kui-loader-border-width': '2px',
    '--kui-loader-duration': '800ms',
    '--kui-skeleton-bg': 'var(--kui-color-skeleton-bg)',
    '--kui-skeleton-highlight': 'var(--kui-color-skeleton-highlight)',
    '--kui-skeleton-radius': 'var(--kui-radius-sm)',
    '--kui-skeleton-radius-pill': 'var(--kui-radius-full)',
    '--kui-skeleton-duration': '1600ms',
    '--kui-skeleton-line-height': '12px',
    '--kui-skeleton-heading-height': '22px',
    '--kui-skeleton-gap': 'var(--kui-space-2)',
    '--kui-empty-padding': 'var(--kui-space-12) var(--kui-space-6)',
    '--kui-empty-padding-sm': 'var(--kui-space-3)',
    '--kui-empty-padding-lg': 'var(--kui-space-16) var(--kui-space-8)',
    '--kui-empty-gap': 'var(--kui-space-3)',
    '--kui-empty-body-gap': 'var(--kui-space-1)',
    '--kui-empty-actions-gap': 'var(--kui-space-2)',
    '--kui-empty-max-width': '360px',
    '--kui-empty-max-width-lg': '440px',
    '--kui-empty-icon-size-sm': '20px',
    '--kui-empty-icon-size-md': '40px',
    '--kui-empty-icon-size-lg': '56px',
    '--kui-empty-icon-color': 'var(--kui-color-text-secondary)',
    '--kui-empty-title-color': 'var(--kui-color-text)',
    '--kui-empty-title-size': 'var(--kui-text-md-size)',
    '--kui-empty-title-weight': '650',
    '--kui-empty-description-color': 'var(--kui-color-text-secondary)',
    '--kui-empty-description-size': 'var(--kui-text-sm-size)',
    '--kui-avatar-size-xs': '20px',
    '--kui-avatar-size-sm': '24px',
    '--kui-avatar-size-md': '32px',
    '--kui-avatar-size-lg': '40px',
    '--kui-avatar-size-xl': '48px',
    '--kui-avatar-size-2xl': '64px',
    '--kui-avatar-font-size-xs': 'var(--kui-text-2xs-size)',
    '--kui-avatar-font-size-sm': 'var(--kui-text-xs-size)',
    '--kui-avatar-font-size-md': 'var(--kui-text-sm-size)',
    '--kui-avatar-font-size-lg': 'var(--kui-text-md-size)',
    '--kui-avatar-font-size-xl': 'var(--kui-text-lg-size)',
    '--kui-avatar-font-size-2xl': 'var(--kui-text-xl-size)',
    '--kui-avatar-radius-circle': '50%',
    '--kui-avatar-radius-square': 'var(--kui-radius-sm)',
    '--kui-avatar-radius-square-sm': 'var(--kui-radius-xs)',
    '--kui-avatar-radius-square-lg': 'var(--kui-radius-md)',
    '--kui-avatar-radius-square-xl': 'var(--kui-radius-lg)',
    '--kui-avatar-radius-square-2xl': 'var(--kui-radius-xl)',
    '--kui-avatar-bg-fallback': 'var(--kui-color-surface-elevated)',
    '--kui-avatar-icon-color': 'var(--kui-color-text-secondary)',
    '--kui-avatar-font-weight': '600',
    '--kui-avatar-border': '0',
    '--kui-avatar-status-border': 'var(--kui-color-bg)',
    '--kui-avatar-status-size-xs': '5px',
    '--kui-avatar-status-size-sm': '6px',
    '--kui-avatar-status-size-md': '9px',
    '--kui-avatar-status-size-lg': '11px',
    '--kui-avatar-status-size-xl': '13px',
    '--kui-avatar-status-size-2xl': '17px',
    '--kui-avatar-status-border-width-xs': '1px',
    '--kui-avatar-status-border-width-sm': '1.5px',
    '--kui-avatar-status-border-width-md': '2px',
    '--kui-avatar-status-border-width-lg': '2px',
    '--kui-avatar-status-border-width-xl': '2.5px',
    '--kui-avatar-status-border-width-2xl': '3px',
    '--kui-avatar-group-overlap-xs': '5px',
    '--kui-avatar-group-overlap-sm': '6px',
    '--kui-avatar-group-overlap-md': '8px',
    '--kui-avatar-group-overlap-lg': '10px',
    '--kui-avatar-group-overlap-xl': '12px',
    '--kui-avatar-group-overlap-2xl': '16px',
    '--kui-avatar-overflow-bg': 'var(--kui-color-surface-elevated)',
    '--kui-avatar-overflow-text': 'var(--kui-color-text-secondary)',
    '--kui-avatar-overflow-font-size': 'var(--kui-text-xs-size)',
    '--kui-avatar-skeleton-bg': 'var(--kui-color-surface-elevated)',
    '--kui-avatar-skeleton-shine': 'var(--kui-color-border-strong)',
    '--kui-avatar-skeleton-duration': '1400ms',
    '--kui-avatar-overlay-hover': 'oklch(0 0 0 / 0.20)',
    '--kui-avatar-overlay-active': 'oklch(0 0 0 / 0.30)',
    '--kui-avatar-action-radius': 'var(--kui-radius-full)',
    '--kui-avatar-focus-ring-w': '3px',
    '--kui-avatar-focus-ring-off': '2px',
    '--kui-avatar-focus-ring-color': 'var(--kui-color-primary-focus-ring)',
    '--kui-slider-thumb-shadow': '0 1px 3px oklch(0 0 0 / 0.45), 0 0 0 1.5px oklch(0 0 0 / 0.12)',
    '--kui-slider-thumb-shadow-hover':
      '0 0 0 5px oklch(0.67 0.2125 285 / 0.22), 0 1px 3px oklch(0 0 0 / 0.30)',
    '--kui-slider-thumb-shadow-focus':
      '0 0 0 3px var(--kui-color-primary-focus-ring), 0 1px 2px oklch(0 0 0 / 0.30)',
    '--kui-slider-thumb-shadow-active':
      '0 2px 8px oklch(0 0 0 / 0.50), 0 0 0 4px oklch(0.67 0.2125 285 / 0.15)',
    '--kui-card-bg': 'var(--kui-color-surface)',
    '--kui-card-bg-elevated': 'var(--kui-color-surface-elevated)',
    '--kui-card-bg-sunken': 'var(--kui-color-surface-sunken)',
    '--kui-card-border': 'var(--kui-color-border)',
    '--kui-card-border-elevated': 'var(--kui-color-border-strong)',
    '--kui-card-border-sunken': 'var(--kui-color-border)',
    '--kui-card-border-hover': 'var(--kui-color-border-strong)',
    '--kui-card-radius': 'var(--kui-radius-md)',
    '--kui-card-padding': 'var(--kui-space-4)',
    '--kui-card-shadow': 'none',
    '--kui-card-shadow-elevated': '0 10px 28px oklch(0 0 0 / 0.18)',
    '--kui-card-shadow-sunken': 'none',
    '--kui-card-shadow-hover': '0 10px 30px oklch(0 0 0 / 0.14)',
    '--kui-shadow-lg': '0 8px 24px oklch(0 0 0 / 0.18), 0 2px 8px oklch(0 0 0 / 0.10)',
    '--kui-tooltip-bg': 'var(--kui-color-text)',
    '--kui-tooltip-fg': 'var(--kui-color-bg)',
    '--kui-tooltip-px': '9px',
    '--kui-tooltip-py': '5px',
    '--kui-tooltip-radius': 'var(--kui-radius-sm)',
    '--kui-tooltip-shadow': 'var(--kui-shadow-lg)',
    '--kui-tabs-border': 'var(--kui-color-border)',
    '--kui-tabs-gap': '2px',
    '--kui-tabs-panel-gap': 'var(--kui-space-4)',
    '--kui-tab-height': 'var(--kui-btn-height)',
    '--kui-tab-px': 'var(--kui-btn-px)',
    '--kui-tab-gap': 'var(--kui-space-1)',
    '--kui-tab-radius': 'var(--kui-radius-sm)',
    '--kui-tab-font-size': 'var(--kui-btn-font-size)',
    '--kui-tab-font-weight': '500',
    '--kui-tab-font-weight-active': '600',
    '--kui-tab-fg': 'var(--kui-color-text-secondary)',
    '--kui-tab-fg-hover': 'var(--kui-color-text)',
    '--kui-tab-fg-active': 'var(--kui-color-text)',
    '--kui-tab-bg-hover': 'var(--kui-color-surface-sunken)',
    '--kui-tab-indicator': 'var(--kui-color-primary-fill)',
    '--kui-seg-bg': 'var(--kui-color-surface-sunken)',
    '--kui-seg-border': 'var(--kui-color-border)',
    '--kui-seg-radius': 'var(--kui-radius-md)',
    '--kui-seg-padding': '4px',
    '--kui-seg-gap': '2px',
    '--kui-seg-height': 'calc(var(--kui-btn-height) - 2 * var(--kui-seg-padding) - 2px)',
    '--kui-seg-px': 'var(--kui-btn-px)',
    '--kui-seg-item-gap': 'var(--kui-space-1)',
    '--kui-seg-item-radius': 'var(--kui-radius-sm)',
    '--kui-seg-font-size': 'var(--kui-btn-font-size)',
    '--kui-seg-font-weight': '500',
    '--kui-seg-font-weight-active': '600',
    '--kui-seg-fg': 'var(--kui-color-text-secondary)',
    '--kui-seg-fg-hover': 'var(--kui-color-text)',
    '--kui-seg-fg-active': 'var(--kui-btn-solid-fg)',
    '--kui-seg-item-bg-active': 'var(--kui-color-primary-fill)',
    '--kui-seg-item-shadow-active': 'none',
    '--kui-table-border': 'var(--kui-color-border)',
    '--kui-table-bg': 'var(--kui-color-surface)',
    '--kui-table-th-bg': 'var(--kui-color-surface-sunken)',
    '--kui-table-th-fg': 'var(--kui-color-text-secondary)',
    '--kui-table-row-border': 'var(--kui-color-border-subtle, var(--kui-color-border))',
    '--kui-table-row-hover-bg': 'var(--kui-color-primary-soft-bg)',
    '--kui-table-row-selected-bg': 'var(--kui-color-primary-soft-bg)',
    '--kui-table-row-selected-accent': 'var(--kui-color-primary-fill)',
    '--kui-table-sort-active-color': 'var(--kui-color-primary-fill)',
    '--kui-field-action-size': '24px',
    '--kui-field-action-icon-size': '14px',
    '--kui-field-action-radius': 'var(--kui-radius-sm)',
    '--kui-field-action-color': 'var(--kui-color-text-secondary)',
    '--kui-field-action-color-hover': 'var(--kui-color-text)',
    '--kui-field-action-color-active': 'var(--kui-color-text)',
    '--kui-field-action-bg-hover': 'var(--kui-color-surface-elevated)',
    '--kui-field-action-bg-active': 'var(--kui-color-surface-sunken)',
    '--kui-field-action-focus-ring-width': '2px',
    '--kui-field-action-focus-ring-color': 'var(--kui-color-primary-focus-ring)',
    '--kui-field-action-disabled-opacity': '0.5',
    '--kui-select-bg': 'var(--kui-color-surface)',
    '--kui-select-border': 'var(--kui-color-border)',
    '--kui-select-border-hover': 'var(--kui-color-border-strong)',
    '--kui-select-border-focus': 'var(--kui-color-primary-fill)',
    '--kui-select-border-error': 'var(--kui-color-danger-fill)',
    '--kui-select-radius': 'var(--kui-radius-md)',
    '--kui-select-dropdown-bg': 'var(--kui-color-surface-elevated)',
    '--kui-select-option-hover-bg': 'var(--kui-color-surface-sunken)',
    '--kui-select-option-selected-bg': 'var(--kui-color-primary-soft-bg)',
    '--kui-select-option-selected-fg': 'var(--kui-color-primary-soft-text)',
    '--kui-select-affordance-size': 'var(--kui-field-action-size)',
    '--kui-select-suffix-inline-end': '10px',
    '--kui-select-suffix-gap': 'var(--kui-space-1)',
    '--kui-select-chip-layer-inline-start': 'var(--kui-space-2)',
    '--kui-select-chip-layer-inline-end': '64px',
    '--kui-select-chip-layer-gap': 'var(--kui-space-1)',
    '--kui-dialog-bg': 'var(--kui-color-surface-elevated)',
    '--kui-dialog-border': 'var(--kui-color-border)',
    '--kui-dialog-radius': 'var(--kui-radius-lg)',
    '--kui-dialog-shadow': 'var(--kui-shadow-lg)',
    '--kui-dialog-backdrop': 'oklch(0 0 0 / 0.5)',
    '--kui-dialog-padding-x': 'var(--kui-space-6)',
    '--kui-dialog-padding-y': 'var(--kui-space-4)',
    '--kui-dialog-title-size': 'var(--kui-text-lg-size)',
    '--kui-toast-bg': 'var(--kui-color-surface-elevated)',
    '--kui-toast-border': 'var(--kui-color-border)',
    '--kui-toast-radius': 'var(--kui-radius-md)',
    '--kui-toast-shadow': 'var(--kui-shadow-lg)',
    '--kui-toast-padding-x': 'var(--kui-space-4)',
    '--kui-toast-padding-y': 'var(--kui-space-3)',
    '--kui-toast-gap': 'var(--kui-space-3)',
    '--kui-toast-stack-gap': 'var(--kui-space-2)',
    '--kui-toast-title-size': 'var(--kui-text-sm-size)',
    '--kui-toast-message-size': 'var(--kui-text-sm-size)',
    '--kui-toast-region-offset': 'var(--kui-space-4)',
    '--kui-toast-min-width': '280px',
    '--kui-toast-max-width': '400px',
    '--kui-popover-bg': 'var(--kui-color-surface-elevated)',
    '--kui-popover-border': 'var(--kui-color-border)',
    '--kui-popover-radius': 'var(--kui-radius-lg)',
    '--kui-popover-shadow': 'var(--kui-shadow-lg)',
    '--kui-popover-padding-x': 'var(--kui-space-4)',
    '--kui-popover-padding-y': 'var(--kui-space-4)',
    '--kui-popover-min-width': '160px',
    '--kui-popover-max-width': '320px',
    '--kui-popover-arrow-size': '10px',
    '--kui-z-popover': '400',
    '--kui-menu-bg': 'var(--kui-color-surface-elevated)',
    '--kui-menu-border': 'var(--kui-color-border)',
    '--kui-menu-border-width': '1px',
    '--kui-menu-radius': 'var(--kui-radius-md)',
    '--kui-menu-shadow': 'var(--kui-shadow-lg)',
    '--kui-menu-padding-y': 'var(--kui-space-1)',
    '--kui-menu-padding-x': 'var(--kui-space-1)',
    '--kui-menu-min-width': '160px',
    '--kui-menu-item-height': '32px',
    '--kui-menu-item-height-mobile': '44px',
    '--kui-menu-item-padding-x': 'var(--kui-space-3)',
    '--kui-menu-item-gap': 'var(--kui-space-2)',
    '--kui-menu-item-radius': 'var(--kui-radius-sm)',
    '--kui-menu-item-font-size': 'var(--kui-text-sm-size)',
    '--kui-menu-item-font-weight': '500',
    '--kui-menu-item-text': 'var(--kui-color-text)',
    '--kui-menu-item-text-destructive': 'var(--kui-color-danger-fill)',
    '--kui-menu-item-text-disabled': 'var(--kui-color-text-disabled)',
    '--kui-menu-item-bg-hover': 'var(--kui-color-surface-sunken)',
    '--kui-menu-item-bg-active': 'var(--kui-color-surface-sunken)',
    '--kui-menu-item-icon-size': '16px',
    '--kui-menu-item-icon-color': 'var(--kui-color-text-secondary)',
    '--kui-menu-item-shortcut-text': 'var(--kui-color-text-secondary)',
    '--kui-menu-group-header-text': 'var(--kui-color-text-secondary)',
    '--kui-menu-group-header-py-start': 'var(--kui-space-2)',
    '--kui-menu-group-header-py-end': 'var(--kui-space-1)',
    '--kui-menu-group-header-font-size': 'var(--kui-text-xs-size)',
    '--kui-menu-group-header-font-weight': '600',
    '--kui-z-menu': '420',
    '--kui-separator-color-subtle': 'var(--kui-color-border-subtle)',
    '--kui-separator-color-default': 'var(--kui-color-border)',
    '--kui-separator-color-strong': 'var(--kui-color-border-strong)',
    '--kui-separator-thickness': '1px',
    '--kui-separator-vertical-min-block-size': 'var(--kui-space-4)',
    '--kui-separator-spacing-none': '0',
    '--kui-separator-spacing-xs': 'var(--kui-space-1)',
    '--kui-separator-spacing-sm': 'var(--kui-space-3)',
    '--kui-separator-spacing-md': 'var(--kui-space-4)',
    '--kui-separator-spacing-lg': 'var(--kui-space-6)',
    '--kui-drawer-bg': 'var(--kui-color-surface-elevated)',
    '--kui-drawer-border': 'var(--kui-color-border)',
    '--kui-drawer-border-width': '1px',
    '--kui-drawer-radius': 'var(--kui-radius-lg)',
    '--kui-drawer-backdrop-bg': 'oklch(0 0 0 / 0.5)',
    '--kui-drawer-shadow-right': '-4px 0 24px oklch(0 0 0 / 0.18)',
    '--kui-drawer-shadow-left': '4px 0 24px oklch(0 0 0 / 0.18)',
    '--kui-drawer-shadow-bottom': '0 -4px 24px oklch(0 0 0 / 0.18)',
    '--kui-drawer-shadow-top': '0 4px 24px oklch(0 0 0 / 0.18)',
    '--kui-drawer-header-height': '56px',
    '--kui-drawer-header-padding-x': 'var(--kui-space-6)',
    '--kui-drawer-header-padding-y': 'var(--kui-space-4)',
    '--kui-drawer-title-size': 'var(--kui-text-base-size)',
    '--kui-drawer-title-weight': '600',
    '--kui-drawer-close-size': '28px',
    '--kui-drawer-body-padding': 'var(--kui-space-6)',
    '--kui-drawer-footer-height': '56px',
    '--kui-drawer-footer-padding-x': 'var(--kui-space-6)',
    '--kui-drawer-footer-padding-y': 'var(--kui-space-4)',
    '--kui-drawer-width-sm': '320px',
    '--kui-drawer-width-md': '480px',
    '--kui-drawer-width-lg': '640px',
    '--kui-drawer-height-sm': '40vh',
    '--kui-drawer-height-md': '50vh',
    '--kui-drawer-height-lg': '70vh',
    '--kui-drawer-duration-open': '280ms',
    '--kui-drawer-duration-close': '220ms',
    '--kui-z-drawer-backdrop': '500',
    '--kui-z-drawer': '510',
    '--kui-chip-bg': 'var(--kui-color-surface-elevated)',
    '--kui-chip-bg-hover': 'var(--kui-color-border)',
    '--kui-chip-border': 'var(--kui-color-border)',
    '--kui-chip-border-width': '1px',
    '--kui-chip-text': 'var(--kui-color-text)',
    '--kui-chip-radius': 'var(--kui-radius-sm)',
    '--kui-chip-height-xs': '18px',
    '--kui-chip-height-sm': '22px',
    '--kui-chip-height-md': '26px',
    '--kui-chip-height-lg': '32px',
    '--kui-chip-padding-x': '10px',
    '--kui-chip-gap-xs': '3px',
    '--kui-chip-gap-sm': 'var(--kui-space-1)',
    '--kui-chip-gap-md': 'var(--kui-space-1)',
    '--kui-chip-gap-lg': 'var(--kui-space-1)',
    '--kui-chip-font-size-xs': 'var(--kui-text-2xs-size)',
    '--kui-chip-font-size-sm': 'var(--kui-text-xs-size)',
    '--kui-chip-font-size-md': 'var(--kui-text-sm-size)',
    '--kui-chip-font-size-lg': 'var(--kui-text-sm-size)',
    '--kui-chip-font-weight': '600',
    '--kui-chip-disabled-opacity': '0.4',
    '--kui-chip-focus-ring-width': '3px',
    '--kui-chip-icon-opacity': '0.75',
    '--kui-chip-avatar-font-weight': '700',
    '--kui-chip-remove-color': 'var(--kui-color-text-secondary)',
    '--kui-chip-remove-color-hover': 'var(--kui-color-text)',
    '--kui-chip-remove-radius': '2px',
    '--kui-chip-remove-size-xs': '10px',
    '--kui-chip-remove-size-sm': '12px',
    '--kui-chip-remove-size-md': '14px',
    '--kui-chip-remove-size-lg': '18px',
    '--kui-chip-remove-focus-ring-width': '2px',
    '--kui-combobox-bg': 'var(--kui-color-surface)',
    '--kui-combobox-border': 'var(--kui-color-border)',
    '--kui-combobox-border-hover': 'var(--kui-color-border-strong)',
    '--kui-combobox-border-focus': 'var(--kui-color-primary-fill)',
    '--kui-combobox-border-error': 'var(--kui-color-danger-fill)',
    '--kui-combobox-border-width': '1px',
    '--kui-combobox-radius': 'var(--kui-radius-md)',
    '--kui-combobox-height-sm': 'var(--kui-control-height-xs)',
    '--kui-combobox-height-md': 'var(--kui-control-height-md)',
    '--kui-combobox-height-lg': 'var(--kui-control-height-lg)',
    '--kui-combobox-suffix-space-sm': '52px',
    '--kui-combobox-suffix-space-md': '64px',
    '--kui-combobox-suffix-space-lg': '72px',
    '--kui-combobox-suffix-gap': '2px',
    '--kui-combobox-affordance-size': '20px',
    '--kui-combobox-focus-ring-width': '3px',
    '--kui-combobox-disabled-opacity': '0.6',
    '--kui-combobox-input-min-width': '72px',
    '--kui-combobox-list-max-height': '280px',
    '--kui-combobox-loader-size': '16px',
    '--kui-combobox-loader-border-width': '2px',
    '--kui-combobox-loader-duration': '700ms',
    '--kui-z-combobox': '430',
  };
}

function parseKuiColor(color: string): KuiOklchColor {
  if (color.startsWith('#')) {
    return hexToOklch(color);
  }

  const match = /^oklch\(\s*([0-9.]+%?)\s+([0-9.]+)\s+([0-9.]+)(?:\s*\/\s*([0-9.]+))?\s*\)$/i.exec(
    color,
  );

  if (!match) {
    throw new Error(`Unsupported Kikita UI seed color "${color}". Use hex or oklch().`);
  }

  return {
    lightness: parseLightness(match[1]),
    chroma: Number(match[2]),
    hue: normalizeHue(Number(match[3])),
    alpha: match[4] === undefined ? undefined : Number(match[4]),
  };
}

function parseLightness(value: string): number {
  return value.endsWith('%') ? Number(value.slice(0, -1)) / 100 : Number(value);
}

function hexToOklch(hex: string): KuiOklchColor {
  const normalized =
    hex.length === 4 ? `#${hex[1]}${hex[1]}${hex[2]}${hex[2]}${hex[3]}${hex[3]}` : hex;

  if (!/^#[0-9a-f]{6}$/i.test(normalized)) {
    throw new Error(`Unsupported hex color "${hex}". Use #rgb or #rrggbb.`);
  }

  const red = srgbToLinear(parseInt(normalized.slice(1, 3), 16) / 255);
  const green = srgbToLinear(parseInt(normalized.slice(3, 5), 16) / 255);
  const blue = srgbToLinear(parseInt(normalized.slice(5, 7), 16) / 255);

  const l = Math.cbrt(0.4122214708 * red + 0.5363325363 * green + 0.0514459929 * blue);
  const m = Math.cbrt(0.2119034982 * red + 0.6806995451 * green + 0.1073969566 * blue);
  const s = Math.cbrt(0.0883024619 * red + 0.2817188376 * green + 0.6299787005 * blue);

  const lightness = 0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s;
  const a = 1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s;
  const b = 0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s;
  const chroma = Math.sqrt(a * a + b * b);
  const hue = normalizeHue((Math.atan2(b, a) * 180) / Math.PI);

  return { lightness, chroma, hue };
}

function srgbToLinear(value: number): number {
  return value <= 0.04045 ? value / 12.92 : ((value + 0.055) / 1.055) ** 2.4;
}

function formatOklch(color: KuiOklchColor): string {
  const base = `oklch(${round(color.lightness)} ${round(color.chroma)} ${round(color.hue)})`;
  return color.alpha === undefined ? base : base.replace(')', ` / ${round(color.alpha)})`);
}

function round(value: number): string {
  return Number(value.toFixed(4)).toString();
}

function normalizeHue(hue: number): number {
  return ((hue % 360) + 360) % 360;
}
