import type { KuiCssVariableMap } from '../kui-theme-tokens.interface';

/** Dialog, toast, popover, menu, drawer, chip, combobox, command palette, tree and chart tokens, and the layer scale. */
export function createOverlayTokens(): KuiCssVariableMap {
  return {
    '--kui-dialog-backdrop': 'oklch(0 0 0 / 0.5)',
    '--kui-dialog-min-width-auto': '320px',
    '--kui-dialog-icon-size': '20px',
    '--kui-dialog-close-size': '28px',
    '--kui-toast-min-width': '280px',
    '--kui-toast-max-width': '400px',
    '--kui-z-toast': '1100',
    '--kui-popover-min-width': '160px',
    '--kui-popover-max-width': '320px',
    '--kui-popover-arrow-size': '10px',
    '--kui-z-popover': '400',
    '--kui-menu-border-width': '1px',
    '--kui-menu-min-width': '160px',
    '--kui-menu-item-height': '32px',
    '--kui-menu-item-height-mobile': '44px',
    '--kui-menu-item-font-weight': '500',
    '--kui-menu-item-icon-size': '16px',
    '--kui-menu-group-header-font-weight': '600',
    '--kui-z-menu': '420',
    '--kui-separator-thickness': '1px',
    '--kui-separator-spacing-none': '0',
    '--kui-drawer-border-width': '1px',
    '--kui-drawer-backdrop-bg': 'oklch(0 0 0 / 0.5)',
    '--kui-drawer-shadow-right': '-4px 0 24px oklch(0 0 0 / 0.18)',
    '--kui-drawer-shadow-left': '4px 0 24px oklch(0 0 0 / 0.18)',
    '--kui-drawer-shadow-bottom': '0 -4px 24px oklch(0 0 0 / 0.18)',
    '--kui-drawer-shadow-top': '0 4px 24px oklch(0 0 0 / 0.18)',
    '--kui-drawer-header-height': '56px',
    '--kui-drawer-title-weight': '600',
    '--kui-drawer-close-size': '28px',
    '--kui-drawer-footer-height': '56px',
    '--kui-drawer-width-sm': '320px',
    '--kui-drawer-width-md': '480px',
    '--kui-drawer-width-lg': '640px',
    '--kui-drawer-height-sm': '40vh',
    '--kui-drawer-height-md': '50vh',
    '--kui-drawer-height-lg': '70vh',
    '--kui-drawer-duration-open': '280ms',
    '--kui-drawer-duration-close': '220ms',
    '--kui-z-drawer-backdrop': '500',
    '--kui-z-drawer': '510',
    '--kui-chip-border-width': '1px',
    '--kui-chip-height-xs': '18px',
    '--kui-chip-height-sm': '22px',
    '--kui-chip-height-md': '26px',
    '--kui-chip-height-lg': '32px',
    '--kui-chip-padding-x': '10px',
    '--kui-chip-gap-xs': '3px',
    '--kui-chip-font-weight': '600',
    '--kui-chip-disabled-opacity': '0.4',
    '--kui-chip-focus-ring-width': '3px',
    '--kui-chip-icon-opacity': '0.75',
    '--kui-chip-avatar-font-weight': '700',
    '--kui-chip-remove-radius': '2px',
    '--kui-chip-remove-size-xs': '10px',
    '--kui-chip-remove-size-sm': '12px',
    '--kui-chip-remove-size-md': '14px',
    '--kui-chip-remove-size-lg': '18px',
    '--kui-chip-remove-focus-ring-width': '2px',
    '--kui-combobox-suffix-gap': '2px',
    '--kui-combobox-affordance-size': '20px',
    '--kui-combobox-loader-size': '16px',
    '--kui-combobox-loader-border-width': '2px',
    '--kui-combobox-loader-duration': '700ms',
    '--kui-command-backdrop-bg': 'oklch(0 0 0 / 0.5)',
    '--kui-command-width': 'min(640px, 90vw)',
    '--kui-command-max-height': '78vh',
    '--kui-command-offset-block-start': '12vh',
    '--kui-command-search-height': '52px',
    '--kui-command-list-max-height': '320px',
    '--kui-command-item-height': '40px',
    '--kui-z-command-palette': '460',
    '--kui-z-overlay': '1000',
    '--kui-z-dialog': '520',
    '--kui-z-dropdown': '1000',
    '--kui-z-tooltip': '9000',
    '--kui-breadcrumb-font-weight-current': '600',
    '--kui-date-picker-suffix-gap': '2px',
    '--kui-date-picker-affordance-size': '20px',
    '--kui-tree-indent': '24px',
    '--kui-file-upload-dropzone-bg': 'transparent',
    '--kui-timepicker-affordance-size': '20px',
    '--kui-chart-height-sm': '160px',
    '--kui-chart-height-md': '240px',
    '--kui-chart-height-lg': '320px',
    '--kui-chart-stroke-width': '2px',
    '--kui-chart-point-radius': '4px',
    '--kui-chart-donut-thickness': '28px',
    '--kui-chart-tooltip-radius': 'var(--kui-radius-md)',
  };
}
