import type { KuiCssVariableMap } from '../kui-theme-tokens.interface';

/** Badge, loader, skeleton, scrollbar, empty state, avatar, card, tooltip, tabs and segmented tokens. */
export function createContentTokens(): KuiCssVariableMap {
  return {
    '--kui-badge-font-weight': '600',
    '--kui-loader-duration': '800ms',
    '--kui-skeleton-duration': '1600ms',
    '--kui-skeleton-line-height': '12px',
    '--kui-skeleton-heading-height': '22px',
    '--kui-skeleton-gap': 'var(--kui-space-2)',
    '--kui-scrollbar-size': '10px',
    '--kui-scrollbar-track': 'transparent',
    '--kui-scrollbar-thumb-min': '32px',
    '--kui-scrollbar-thumb-inset': '2px',
    '--kui-empty-max-width': '360px',
    '--kui-empty-max-width-lg': '440px',
    '--kui-empty-icon-size-sm': '20px',
    '--kui-empty-icon-size-md': '40px',
    '--kui-empty-icon-size-lg': '56px',
    '--kui-empty-title-weight': '650',
    '--kui-avatar-size-xs': '20px',
    '--kui-avatar-size-sm': '24px',
    '--kui-avatar-size-md': '32px',
    '--kui-avatar-size-lg': '40px',
    '--kui-avatar-size-xl': '48px',
    '--kui-avatar-size-2xl': '64px',
    '--kui-avatar-radius-circle': '50%',
    '--kui-avatar-font-weight': '600',
    '--kui-avatar-border': '0',
    '--kui-avatar-status-size-xs': '5px',
    '--kui-avatar-status-size-sm': '6px',
    '--kui-avatar-status-size-md': '9px',
    '--kui-avatar-status-size-lg': '11px',
    '--kui-avatar-status-size-xl': '13px',
    '--kui-avatar-status-size-2xl': '17px',
    '--kui-avatar-status-border-width-xs': '1px',
    '--kui-avatar-status-border-width-sm': '1.5px',
    '--kui-avatar-status-border-width-md': '2px',
    '--kui-avatar-status-border-width-lg': '2px',
    '--kui-avatar-status-border-width-xl': '2.5px',
    '--kui-avatar-status-border-width-2xl': '3px',
    '--kui-avatar-group-overlap-xs': '5px',
    '--kui-avatar-group-overlap-sm': '6px',
    '--kui-avatar-group-overlap-md': '8px',
    '--kui-avatar-group-overlap-lg': '10px',
    '--kui-avatar-group-overlap-xl': '12px',
    '--kui-avatar-group-overlap-2xl': '16px',
    '--kui-avatar-overlay-hover': 'oklch(0 0 0 / 0.20)',
    '--kui-avatar-overlay-active': 'oklch(0 0 0 / 0.30)',
    '--kui-avatar-focus-ring-w': '3px',
    '--kui-avatar-focus-ring-off': '2px',
    '--kui-slider-thumb-shadow': '0 1px 3px oklch(0 0 0 / 0.45), 0 0 0 1.5px oklch(0 0 0 / 0.12)',
    '--kui-card-shadow': 'none',
    '--kui-card-shadow-elevated': '0 10px 28px oklch(0 0 0 / 0.18)',
    '--kui-card-shadow-sunken': 'none',
    '--kui-card-shadow-hover': '0 10px 30px oklch(0 0 0 / 0.14)',
    '--kui-shadow-lg': '0 8px 24px oklch(0 0 0 / 0.18), 0 2px 8px oklch(0 0 0 / 0.10)',
    '--kui-tooltip-px': '9px',
    '--kui-tooltip-py': '5px',
    '--kui-tabs-gap': '2px',
    '--kui-tab-font-weight': '500',
    '--kui-tab-font-weight-active': '600',
    '--kui-seg-padding': '2px',
    '--kui-seg-gap': '2px',
    '--kui-seg-font-weight': '500',
    '--kui-seg-font-weight-active': '600',
    '--kui-seg-item-shadow-active': 'none',
  };
}
