import type { KuiThemeOptions } from '../kui-theme-options.interface';
import type { KuiCssVariableMap } from '../kui-theme-tokens.interface';

/**
 * Typography, spacing, radius, border, control height, button and motion tokens. The seeds that
 * reach component tokens (radius and density) enter here. The five token files are consecutive
 * slices of one table, so the order of the declarations in the generated CSS is unchanged.
 */
export function createFoundationTokens(options: KuiThemeOptions): KuiCssVariableMap {
  const radius = `${options.seeds.radius}px`;
  const density = options.seeds.density;

  return {
    '--kui-font-sans':
      'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    '--kui-font-mono': 'ui-monospace, "SFMono-Regular", Consolas, "Liberation Mono", monospace',
    '--kui-radius-none': '0',
    '--kui-radius-xs': `${Math.max(2, options.seeds.radius - 4)}px`,
    '--kui-radius-sm': `${Math.max(4, options.seeds.radius - 2)}px`,
    '--kui-radius-md': radius,
    '--kui-radius-lg': `${options.seeds.radius + 2}px`,
    '--kui-radius-xl': `${options.seeds.radius + 6}px`,
    '--kui-radius-full': '9999px',
    /** @deprecated Constant white kept for 2.x consumers. Use `--kui-color-<role>-on-fill`. Removed in 3.0. */
    '--kui-color-on-fill': 'oklch(1 0 0)',
    '--kui-border-width-hairline': '1px',
    '--kui-border-width-thick': '1.5px',
    '--kui-border-width-heavy': '2px',
    '--kui-focus-ring-width': '3px',
    '--kui-focus-ring-width-sm': '2px',
    '--kui-focus-ring-offset': '2px',
    '--kui-focus-ring-offset-inset': '-2px',
    '--kui-opacity-disabled': '0.5',
    '--kui-space-0-5': '2px',
    '--kui-space-1': '4px',
    '--kui-space-1-5': '6px',
    '--kui-space-2': '8px',
    '--kui-space-3': '12px',
    '--kui-space-4': '16px',
    '--kui-space-5': '20px',
    '--kui-space-6': '24px',
    '--kui-space-8': '32px',
    '--kui-space-12': '48px',
    '--kui-space-16': '64px',
    '--kui-text-2xs-size': '9px',
    '--kui-text-xs-size': '11px',
    '--kui-text-sm-size': '13px',
    '--kui-text-base-size': '14px',
    '--kui-text-md-size': '15px',
    '--kui-text-lg-size': '18px',
    '--kui-text-xl-size': '22px',
    '--kui-text-2xl-size': '28px',
    '--kui-text-3xl-size': '36px',
    '--kui-font-weight-regular': '400',
    '--kui-font-weight-medium': '500',
    '--kui-font-weight-semibold': '600',
    '--kui-font-weight-bold': '700',
    '--kui-type-display-size': 'var(--kui-text-3xl-size)',
    '--kui-type-display-line-height': '1.15',
    '--kui-type-display-weight': 'var(--kui-font-weight-bold)',
    '--kui-type-heading-lg-size': 'var(--kui-text-2xl-size)',
    '--kui-type-heading-lg-line-height': '1.2',
    '--kui-type-heading-lg-weight': 'var(--kui-font-weight-bold)',
    '--kui-type-heading-md-size': 'var(--kui-text-xl-size)',
    '--kui-type-heading-md-line-height': '1.25',
    '--kui-type-heading-md-weight': 'var(--kui-font-weight-semibold)',
    '--kui-type-heading-sm-size': 'var(--kui-text-lg-size)',
    '--kui-type-heading-sm-line-height': '1.3',
    '--kui-type-heading-sm-weight': 'var(--kui-font-weight-semibold)',
    '--kui-type-title-size': 'var(--kui-text-base-size)',
    '--kui-type-title-line-height': '1.4',
    '--kui-type-title-weight': 'var(--kui-font-weight-semibold)',
    '--kui-type-body-lg-size': 'var(--kui-text-md-size)',
    '--kui-type-body-lg-line-height': '1.6',
    '--kui-type-body-lg-weight': 'var(--kui-font-weight-regular)',
    '--kui-type-body-size': 'var(--kui-text-base-size)',
    '--kui-type-body-line-height': '1.5',
    '--kui-type-body-weight': 'var(--kui-font-weight-regular)',
    '--kui-type-body-sm-size': 'var(--kui-text-sm-size)',
    '--kui-type-body-sm-line-height': '1.5',
    '--kui-type-body-sm-weight': 'var(--kui-font-weight-regular)',
    '--kui-type-caption-size': 'var(--kui-text-xs-size)',
    '--kui-type-caption-line-height': '1.5',
    '--kui-type-caption-weight': 'var(--kui-font-weight-regular)',
    '--kui-type-overline-size': 'var(--kui-text-2xs-size)',
    '--kui-type-overline-line-height': '1.4',
    '--kui-type-overline-weight': 'var(--kui-font-weight-semibold)',
    '--kui-type-overline-letter-spacing': '0.06em',
    '--kui-type-code-size': 'var(--kui-text-sm-size)',
    '--kui-type-code-line-height': '1.5',
    '--kui-type-code-weight': 'var(--kui-font-weight-regular)',
    '--kui-line-height-control': '1.3',
    '--kui-control-height-xs': '28px',
    '--kui-control-height-sm': '32px',
    '--kui-control-height-md': '40px',
    '--kui-control-height-lg': '44px',
    '--kui-btn-px-compact': '8px',
    '--kui-btn-px-regular': '12px',
    '--kui-btn-px-comfortable': '16px',
    '--kui-btn-px': `var(--kui-btn-px-${density})`,
    '--kui-btn-gap': '6px',
    '--kui-duration-fast': '100ms',
    '--kui-duration-quick': '120ms',
    '--kui-duration-base': '160ms',
    '--kui-duration-normal': '200ms',
    '--kui-ease': 'cubic-bezier(0.16, 1, 0.3, 1)',
    '--kui-ease-exit': 'cubic-bezier(0.4, 0, 1, 1)',
  };
}
