import { Routes } from '@angular/router';

import {
  BadgePage,
  ButtonPage,
  CardPage,
  CheckboxPage,
  DensityPage,
  FieldPage,
  FormsPage,
  GroupPage,
  IconsPage,
  InputPage,
  LoaderPage,
  RadioPage,
  SwitchPage,
  TextareaPage,
  ThemePage,
  TokensPage,
  TooltipPage,
} from './playground-pages';

export const routes: Routes = [
  { path: '', pathMatch: 'full', redirectTo: 'tokens' },
  { path: 'tokens', component: TokensPage },
  { path: 'theme', component: ThemePage },
  { path: 'density', component: DensityPage },
  { path: 'button', component: ButtonPage },
  { path: 'field', component: FieldPage },
  { path: 'input', component: InputPage },
  { path: 'textarea', component: TextareaPage },
  { path: 'checkbox', component: CheckboxPage },
  { path: 'switch', component: SwitchPage },
  { path: 'radio', component: RadioPage },
  { path: 'badge', component: BadgePage },
  { path: 'loader', component: LoaderPage },
  { path: 'card', component: CardPage },
  { path: 'group', component: GroupPage },
  { path: 'icons', component: IconsPage },
  { path: 'forms', component: FormsPage },
  { path: 'tooltip', component: TooltipPage },
  { path: '**', redirectTo: 'tokens' },
];
